services:
  - type: web
    name: helmet-compliance-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.enableCORS false
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
